name: Robot Framework Tests

on:
  pull_request:
    branches:
      - main

jobs:
  robot_framework_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust as needed

    - name: Run Robot Framework Tests
      run: |
        robot tests

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: robot-results
        path: output.xml
